version: "3"
services:
  mongodb:
    image: 'mongo:latest'
    container_name: "mongodb"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  app:
    build: .
    container_name: "uni_app"
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/uni_app
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
