services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - uni_mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/demo
  uni_mongodb:
    image: 'mongo:latest'
    container_name: "uni_mongodb"
    ports:
      - 27017:27017


